LANGUAGES = {
    "ru": {
        "_lang_code": "ru", "language_name": "Русский", "tab_dashboard": "Главная", "tab_store": "Магазин", "tab_library": "Скачанные", "tab_running": "Запущенные", "tab_create": "Создание", "tab_settings": "Настройки",
        "dashboard_title": "Панель управления", "dashboard_subtitle": "Все инструменты SCS — в одном месте", "dashboard_info": "Управляйте установленными утилитами, находите новые инструменты и создавайте собственные проекты.",
        "dashboard_verified": "Проверенных в каталоге", "dashboard_downloaded_count": "Скачано локально", "dashboard_runtimes": "Поддерживаемые среды", "dashboard_version": "Версия приложения", "dashboard_catalog_ready": "каталог доступен", "dashboard_catalog_unavailable": "каталог недоступен",
        "dashboard_about_title": "О приложении", "dashboard_about_text": "SCS Tools Manager - это приложение, помогающие эффективно взаимодействовать между различными инструментами для игр SCS. Здесь Вы можете установить практически любые необходимые инструменты, а даже если не найдёте, то можете создать свой. Удобный дизайн, лёгкий запуск любых инструментов и вся необходимая адаптация для более удобного использования.", "dashboard_features_title": "Как использовать", "dashboard_features_text": "<p><b>Навигация</b><br>В правом верхнем углу находятся кнопки смены языка и выхода. Слева расположен список доступных вкладок. Изначально Вы находитесь на главной странице, откуда и читаете этот текст. Здесь находится вся основная информация.</p><p><b>Настройка и магазин</b><br>Настроить приложение можно во вкладке «Настройки». Для начала использования Вам нужно создать собственную библиотеку инструментов, скачав хотя бы один во вкладке «Магазин». Там можно посмотреть всю необходимую информацию об инструменте. Все инструменты в магазине проверены и безопасны.</p><p><b>Скачанные и запущенные</b><br>Все скачанные аддоны доступны во вкладке «Скачанные», откуда их можно запускать. Любой инструмент можно установить для более удобного использования и быстрого запуска. Запустив инструмент, Вы попадёте на вкладку «Запущенные»: здесь отображаются все открытые инструменты, и между ними удобно переключаться.</p><p><b>Создание</b><br>Во вкладке «Создание» можно собрать собственный уникальный инструмент. На 1 этапе указывается информация об инструменте, на 2 этапе редактируются скрипты и код, а на 3 этапе настраивается дизайн и проводится тестирование.</p><p><b>Публикация</b><br>Инструкция по публикации собственного инструмента будет добавлена во вкладку «Магазин». Всё, теперь Вы готовы пользоваться менеджером инструментов.</p>", "dashboard_socials_title": "Социальные сети", "dashboard_socials_text": "Ссылки автора.", "dashboard_social_empty": "не указано",
        "download_header": "Магазин инструментов", "download_empty": "Нажмите «Обновить», чтобы найти доступные инструменты", "download_refresh_btn": "Обновить",
        "library_header": "Скачанные инструменты", "library_empty": "Здесь появятся скачанные вами инструменты", "launch": "Запустить",
        "create_header": "Создать инструмент", "create_name": "Название инструмента", "create_desc": "Краткое описание", "create_submit": "Создать проект",
        "settings_header": "Настройки", "settings_language": "Язык интерфейса", "settings_theme": "Тема оформления", "status_ready": "Готов к работе",
        "app_tagline": "Универсальный менеджер инструментов для игр SCS", "navigation": "НАВИГАЦИЯ", "about": "О ПРОЕКТЕ", "dashboard_total": "Всего инструментов", "dashboard_downloaded": "Скачано", "dashboard_updated": "Последнее обновление",
        "store_download": "Скачать", "store_version": "Версия", "downloaded_subtitle": "Запускайте и управляйте установленными утилитами", "downloaded_hint": "После загрузки инструмент будет доступен здесь с кнопкой запуска.",
        "create_subtitle": "Заполните базовые данные нового проекта", "create_version": "Версия", "settings_subtitle": "Настройте приложение под себя", "settings_theme_value": "Тёмная", "settings_version": "SCS Tools Manager  •  v1.0.0",
        "download_ready": "Готово", "download_success": "успешно загружен!", "error": "Ошибка", "create_name_required": "Введите название инструмента.", "success": "Успех", "create_success": "Инструмент создан!",
        "tool_info_title": "Информация об инструменте", "copy_selected": "Копировать выбранное", "more_info": "Больше информации", "close": "Закрыть", "application": "ПРИЛОЖЕНИЕ", "running_subtitle": "Открытые инструменты", "open": "Открыть",
        "exit_application": "Выйти", "full_screen": "На весь экран", "exit_full_screen": "Обычный режим",
        "field_archive": "Archive", "field_archive_path": "Archive path", "field_downloaded_at": "Downloaded at", "field_updated_at": "Updated at", "tool_description_missing": "Описание не указано", "tool_version_missing": "Не указана", "tool_logic_failed": "Не удалось запустить логику инструмента", "exe_launched": "EXE-инструмент запущен отдельным окном Windows.", "runtime_missing": "Для инструмента не указан поддерживаемый файл приложения.",
        "exe_starting": "Запуск приложения…", "exe_failed": "Не удалось запустить EXE", "exe_finished": "Приложение завершилось до создания окна.", "exe_window_not_found": "Окно EXE не удалось обнаружить.", "exe_embed_failed": "Не удалось встроить окно EXE",
    },
    "en": {
        "_lang_code": "en", "language_name": "English", "tab_dashboard": "Home", "tab_store": "Store", "tab_library": "Downloaded", "tab_running": "Running", "tab_create": "Create", "tab_settings": "Settings",
        "dashboard_title": "Control centre", "dashboard_subtitle": "All SCS tools in one place", "dashboard_info": "Manage installed utilities, discover new tools and create your own projects.",
        "dashboard_verified": "Verified in catalog", "dashboard_downloaded_count": "Downloaded locally", "dashboard_runtimes": "Supported runtimes", "dashboard_version": "Application version", "dashboard_catalog_ready": "catalog available", "dashboard_catalog_unavailable": "catalog unavailable",
        "dashboard_about_title": "About the app", "dashboard_about_text": "SCS Tools Manager helps you work effectively with a wide range of tools for SCS games. You can install nearly any tool you need and, if you cannot find one, create your own. The app provides a clear design, easy launching of tools, and practical adaptations for a more convenient workflow.", "dashboard_features_title": "How to use", "dashboard_features_text": "<p><b>Navigation</b><br>The language and exit buttons are in the top-right corner. The available pages are listed on the left. You start on the Home page, where the main information is shown.</p><p><b>Settings and Store</b><br>Configure the app in Settings. To begin, build your own library by downloading at least one tool from Store. Each Store page contains the required tool information; all Store tools are verified and safe.</p><p><b>Downloaded and Running</b><br>Downloaded add-ons can be viewed and launched from Downloaded. You can install any tool for faster access. After launching one, the Running page shows every open tool and lets you switch between them.</p><p><b>Create</b><br>Create your own tool in three steps: specify its information, edit scripts and code, then design and test it.</p><p><b>Publishing</b><br>Publishing instructions will be added to Store. You are now ready to use the tools manager.</p>", "dashboard_socials_title": "Social links", "dashboard_socials_text": "Author links.", "dashboard_social_empty": "not set",
        "download_header": "Tools store", "download_empty": "Press Refresh to find available tools", "download_refresh_btn": "Refresh",
        "library_header": "Downloaded tools", "library_empty": "Your downloaded tools will appear here", "launch": "Launch",
        "create_header": "Create a tool", "create_name": "Tool name", "create_desc": "Short description", "create_submit": "Create project",
        "settings_header": "Settings", "settings_language": "Interface language", "settings_theme": "Appearance", "status_ready": "Ready",
        "app_tagline": "Universal tools manager for SCS games", "navigation": "NAVIGATION", "about": "ABOUT THE PROJECT", "dashboard_total": "Total tools", "dashboard_downloaded": "Downloaded", "dashboard_updated": "Last update",
        "store_download": "Download", "store_version": "Version", "downloaded_subtitle": "Launch and manage installed utilities", "downloaded_hint": "After downloading, the tool will be available here with a launch button.",
        "create_subtitle": "Fill in the basic details for a new project", "create_version": "Version", "settings_subtitle": "Make the app your own", "settings_theme_value": "Dark", "settings_version": "SCS Tools Manager  •  v1.0.0",
        "download_ready": "Done", "download_success": "was downloaded successfully!", "error": "Error", "create_name_required": "Enter a tool name.", "success": "Success", "create_success": "Tool created!",
        "tool_info_title": "Tool information", "copy_selected": "Copy selected", "more_info": "More information", "close": "Close", "application": "APPLICATION", "running_subtitle": "Opened Tools", "open": "Open",
        "exit_application": "Exit", "full_screen": "Full screen", "exit_full_screen": "Exit full screen",
        "field_archive": "Archive", "field_archive_path": "Archive path", "field_downloaded_at": "Downloaded at", "field_updated_at": "Updated at", "tool_description_missing": "Description not provided", "tool_version_missing": "Not provided", "tool_logic_failed": "Unable to run the tool logic", "exe_launched": "The EXE tool was launched in a separate Windows window.", "runtime_missing": "No supported application file is specified for this tool.",
        "exe_starting": "Starting application…", "exe_failed": "Unable to start the EXE", "exe_finished": "The application exited before creating its window.", "exe_window_not_found": "The EXE window could not be found.", "exe_embed_failed": "Unable to embed the EXE window",
    },
}
def get_lang(lang_code):
    return LANGUAGES.get(lang_code, LANGUAGES["ru"])


def available_languages():
    """Список доступных языков; новый язык добавляется только в LANGUAGES."""
    return [(code, data["language_name"]) for code, data in LANGUAGES.items()]
